apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
data:
  app.py: |-
    #!/usr/bin/env python
    from flask import Flask 
    import os

    app = Flask(__name__)

    @app.route("/")
    def hello_world():
      return "Hello GitGuardian!"

    @app.route('/pod-id')
    def pod_id():
      return os.environ['HOSTNAME']

    if __name__ == '__main__':
      app.run(host='0.0.0.0', port=5000)

  install.sh: |
    #!/bin/bash

    pip install flask kubernetes