apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      hostNetwork: true
      containers:
      - name: flask-app
        image: python:3.8-slim
        securityContext:
          privileged: true
        command: ["/bin/bash", "-c"]
        args: [/app/install.sh && /app/app.py ]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: config-volume
          mountPath: /app
      volumes:
      - name: config-volume
        configMap:
          name: flask-app-config
          defaultMode: 0755

